#pragma once
//a list of all event
#include "Event.h"
#include "Quit.h"
#include "KeyPress.h"
#include "Player1MoveUp.h"
#include "Player1MoveDown.h"
#include "Player1MoveLeft.h"
#include "Player1MoveRight.h"
#include "ControllerConnected.h"
#include "ControllerDisconnected.h"
#include "ButtonPress.h"
#include "KeyRelease.h"
#include "Player1StopX.h"
#include "Player1StopY.h"
#include "ToggleShowFps.h"
#include "Save.h"
#include "Load.h"
#include "ToggleShowInfo.h"

