#pragma once
//a list of all event
#include "Event.h"
#include "Quit.h"
#include "KeyPress.h"
#include "PlayerMoveUp.h"
#include "PlayerMoveDown.h"
#include "PlayerMoveLeft.h"
#include "PlayerMoveRight.h"
#include "ControllerConnected.h"
#include "ControllerDisconnected.h"
#include "ButtonPress.h"
#include "KeyRelease.h"
#include "PlayerStopX.h"
#include "PlayerStopY.h"
#include "ToggleShowFps.h"
#include "Save.h"
#include "Load.h"
#include "ToggleShowInfo.h"

