#pragma once
//a list of all event
#include "Event.h"
#include "Event\Quit.h"
#include "Event\KeyPress.h"
#include "Event\Player1MoveUp.h"
#include "Event\Player1MoveDown.h"
#include "Event\Player1MoveLeft.h"
#include "Event\Player1MoveRight.h"
#include "Event\ControllerConnected.h"
#include "Event\ControllerDisconnected.h"
#include "Event\ButtonPress.h"
#include "Event\KeyRelease.h"
#include "Event\Player1StopX.h"
#include "Event\Player1StopY.h"
#include "Event\ToggleShowFps.h"
#include "Event\Save.h"
#include "Event\Load.h"
#include "Event\ToggleShowInfo.h"

